### ISSUE TITLE
What should replaceContent do ?

### ISSUE THREAD

**Issue by superguigui** [brindille/brindille-component#1]
We implemented a replaceContent method in Component.js to be able for any component to completely update its template and launch a new parse to maybe find new sub-components and so on.

With something like this :

```html
<div data-component="Parent">
  <div data-component="Son"></div>
</div>
```

To end up with something like that
```html
<div data-component="Parent">
  <div data-component="Daughter"></div>
</div>
```

Should we be able to do this ?
```js
this.replaceContent('<div data-component="Daughter"></div>');
// => only the content change 
```

If yes I don't know why we implemented it like this : 
```js
replaceContent(content) {
    const tempNode = document.createElement('div');
    tempNode.innerHTML = content;
    this.$el.innerHTML = tempNode.firstChild.innerHTML;
    this.parse();
}
```

Because with our exemple we would end with `this.$el === ''`

Shouldn't it be 
```js
replaceContent(content) {
    this.$el.innerHTML = content;
    this.parse();
}
```

@vdaguenet do you remember this ?

**Comment by vdaguenet** [comment]
I think we used `tempNode` because `content` is a String so we have to _domify_ it to be able to use `this.parse()`. But we did not handle the empty content case.

It should be `tempNode.firstChild.outerHTML` instead of  `tempNode.firstChild.innerHTML`. Like so
```javascript
replaceContent(content) {
    const tempNode = document.createElement('div');
    tempNode.innerHTML = content;
    this.$el.innerHTML = tempNode.firstChild.outerHTML;
    this.parse();
}
```

**Comment by superguigui** [comment]
I thought it was about domification too but it seems `this.$el.innerHTML = content;` works perfectly well. The parse detect the new nodes.

**Comment by vdaguenet** [comment]
Well, if we can make a 4 lines function a 2 lines function, let's do it!

**Comment by superguigui** [comment]
Yes !
I pushed it + the corresponding tests in 6935f1d1a9ed3c4ffbb3b51cb0628b5b972f5c1c
