### ISSUE TITLE
Dom parsing optimizations

### ISSUE THREAD

**Issue by superguigui** [brindille/brindille-component#2]
As pointed out by @Efflam,

`dom-walk` should not continue parsing inside a dom-node when it finds a `data-component` attribute.
It's not a real problem in itself because since child parsing will take place before the parent parsing goes on, all the components will already be found (and `data-component` attributes removed).
But dom-walk still does a lot of parsing for nothing. Even though it's painless it feels like we could / should find a better way to parse everything.

We could either:
- Make our own parser 
- Make a fork / PR of dom-walk
- Find another module
- Let it be for now :smile:

**Comment by vdaguenet** [comment]
Yeah it is a great enhancement we should add.

Make our own parser based on dom-walk can be a good solution. With our parser we could detect `data-component` attribute, bypass the dom element and go to the next one.

**Comment by superguigui** [comment]
One year later, removed dependency and made it so that no node is parsed twice !
https://github.com/brindille/brindille-component/commit/785ad072e6d0cbc45f023e35b47572c06c6552ba
